---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      appName: debug
  template:
    metadata:
      labels:
        appName: debug
        netic.dk/network-rules-egress: app-name
        netic.dk/network-component: other-app-name
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 1000
      containers:
      - name: debug-pod
        image: ghcr.io/neticdk/kubernetes-debug-image:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
