---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: <namespace>
  labels:
    appName: debug
    netic.dk/network-rules-egress: app-name
    netic.dk/network-component: other-app-name
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 10001
    runAsGroup: 30001
  containers:
  - name: debug-pod
    image: ghcr.io/neticdk/kubernetes-debug-image:<tag>
    args: ["1800"]
    securityContext:
      capabilities:
        drop:
        - "ALL"
      allowPrivilegeEscalation: false
